export const fedexCountries = [
  {"name":"Afghanistan","code":"AF","status":"shipping"},
  {"name":"Albania","code":"AL","status":"shipping"},
  {"name":"Algeria","code":"DZ","status":"shipping"},
  {"name":"American Samoa","code":"AS","status":"shipping"},
  {"name":"Andorra","code":"AD","status":"shipping"},
  {"name":"Angola","code":"AO","status":"shipping"},
  {"name":"Anguilla","code":"AI","status":"shipping"},
  {"name":"Antigua and Barbuda","code":"AG","status":"shipping"},
  {"name":"Argentina","code":"AR","status":"shipping"},
  {"name":"Armenia","code":"AM","status":"shipping"},
  {"name":"Aruba","code":"AW","status":"shipping"},
  {"name":"Australia","code":"AU","status":"shipping"},
  {"name":"Austria","code":"AT","status":"shipping"},
  {"name":"Azerbaijan","code":"AZ","status":"shipping"},
  {"name":"Bahamas","code":"BS","status":"shipping"},
  {"name":"Bahrain","code":"BH","status":"shipping"},
  {"name":"Bangladesh","code":"BD","status":"shipping"},
  {"name":"Barbados","code":"BB","status":"shipping"},
  {"name":"Belarus","code":"BY","status":"shipping"},
  {"name":"Belgium","code":"BE","status":"shipping"},
  {"name":"Belize","code":"BZ","status":"shipping"},
  {"name":"Benin","code":"BJ","status":"shipping"},
  {"name":"Bermuda","code":"BM","status":"shipping"},
  {"name":"Bhutan","code":"BT","status":"shipping"},
  {"name":"Bolivia","code":"BO","status":"shipping"},
  {"name":"Bonaire, Sint Eustatius and Saba","code":"BQ","status":"shipping"},
  {"name":"Bosnia and Herzegovina","code":"BA","status":"shipping"},
  {"name":"Botswana","code":"BW","status":"shipping"},
  {"name":"Brazil","code":"BR","status":"shipping"},
  {"name":"British Virgin Islands","code":"VG","status":"shipping"},
  {"name":"Brunei","code":"BN","status":"shipping"},
  {"name":"Bulgaria","code":"BG","status":"shipping"},
  {"name":"Burkina Faso","code":"BF","status":"shipping"},
  {"name":"Burundi","code":"BI","status":"shipping"},
  {"name":"Cambodia","code":"KH","status":"shipping"},
  {"name":"Cameroon","code":"CM","status":"shipping"},
  {"name":"Cape Verde","code":"CV","status":"shipping"},
  {"name":"Cayman Islands","code":"KY","status":"shipping"},
  {"name":"Central African Republic","code":"CF","status":"suspended"},
  {"name":"Chad","code":"TD","status":"shipping"},
  {"name":"Chile","code":"CL","status":"shipping"},
  {"name":"China","code":"CN","status":"shipping"},
  {"name":"Colombia","code":"CO","status":"shipping"},
  {"name":"Congo, Democratic Republic of the","code":"CD","status":"shipping"},
  {"name":"Congo","code":"CG","status":"shipping"},
  {"name":"Cook Islands","code":"CK","status":"shipping"},
  {"name":"Costa Rica","code":"CR","status":"shipping"},
  {"name":"Côte d'Ivoire","code":"CI","status":"shipping"},
  {"name":"Croatia","code":"HR","status":"shipping"},
  {"name":"Curaçao","code":"CW","status":"shipping"},
  {"name":"Cyprus","code":"CY","status":"shipping"},
  {"name":"Czechia","code":"CZ","status":"shipping"},
  {"name":"Denmark","code":"DK","status":"shipping"},
  {"name":"Djibouti","code":"DJ","status":"shipping"},
  {"name":"Dominica","code":"DM","status":"shipping"},
  {"name":"Dominican Republic","code":"DO","status":"shipping"},
  {"name":"Ecuador","code":"EC","status":"shipping"},
  {"name":"Egypt","code":"EG","status":"shipping"},
  {"name":"El Salvador","code":"SV","status":"shipping"},
  {"name":"Equatorial Guinea","code":"GQ","status":"suspended"},
  {"name":"Eritrea","code":"ER","status":"shipping"},
  {"name":"Estonia","code":"EE","status":"shipping"},
  {"name":"Ethiopia","code":"ET","status":"shipping"},
  {"name":"Faroe Islands","code":"FO","status":"shipping"},
  {"name":"Fiji","code":"FJ","status":"shipping"},
  {"name":"Finland","code":"FI","status":"shipping"},
  {"name":"France","code":"FR","status":"shipping"},
  {"name":"French Guiana","code":"GF","status":"shipping"},
  {"name":"French Polynesia","code":"PF","status":"shipping"},
  {"name":"Gabon","code":"GA","status":"shipping"},
  {"name":"Gambia","code":"GM","status":"shipping"},
  {"name":"Georgia","code":"GE","status":"shipping"},
  {"name":"Germany","code":"DE","status":"shipping"},
  {"name":"Ghana","code":"GH","status":"shipping"},
  {"name":"Gibraltar","code":"GI","status":"shipping"},
  {"name":"Greece","code":"GR","status":"shipping"},
  {"name":"Greenland","code":"GL","status":"shipping"},
  {"name":"Grenada","code":"GD","status":"shipping"},
  {"name":"Guadeloupe","code":"GP","status":"shipping"},
  {"name":"Guam","code":"GU","status":"shipping"},
  {"name":"Guatemala","code":"GT","status":"shipping"},
  {"name":"Guinea","code":"GN","status":"shipping"},
  {"name":"Guinea-Bissau","code":"GW","status":"suspended"},
  {"name":"Guyana","code":"GY","status":"shipping"},
  {"name":"Haiti","code":"HT","status":"shipping"},
  {"name":"Honduras","code":"HN","status":"shipping"},
  {"name":"Hong Kong SAR, China","code":"HK","status":"shipping"},
  {"name":"Hungary","code":"HU","status":"shipping"},
  {"name":"Iceland","code":"IS","status":"shipping"},
  {"name":"India","code":"IN","status":"shipping"},
  {"name":"Indonesia","code":"ID","status":"shipping"},
  {"name":"Iraq","code":"IQ","status":"shipping"},
  {"name":"Ireland","code":"IE","status":"shipping"},
  {"name":"Israel","code":"IL","status":"shipping"},
  {"name":"Italy","code":"IT","status":"shipping"},
  {"name":"Jamaica","code":"JM","status":"shipping"},
  {"name":"Japan","code":"JP","status":"shipping"},
  {"name":"Jordan","code":"JO","status":"shipping"},
  {"name":"Kazakhstan","code":"KZ","status":"shipping"},
  {"name":"Kenya","code":"KE","status":"shipping"},
  {"name":"Kuwait","code":"KW","status":"shipping"},
  {"name":"Kyrgyzstan","code":"KG","status":"shipping"},
  {"name":"Laos","code":"LA","status":"shipping"},
  {"name":"Latvia","code":"LV","status":"shipping"},
  {"name":"Lebanon","code":"LB","status":"shipping"},
  {"name":"Lesotho","code":"LS","status":"shipping"},
  {"name":"Liberia","code":"LR","status":"shipping"},
  {"name":"Libya","code":"LY","status":"shipping"},
  {"name":"Liechtenstein","code":"LI","status":"shipping"},
  {"name":"Lithuania","code":"LT","status":"shipping"},
  {"name":"Luxembourg","code":"LU","status":"shipping"},
  {"name":"Macao SAR, China","code":"MO","status":"shipping"},
  {"name":"Macedonia","code":"MK","status":"shipping"},
  {"name":"Madagascar","code":"MG","status":"shipping"},
  {"name":"Malawi","code":"MW","status":"shipping"},
  {"name":"Malaysia","code":"MY","status":"shipping"},
  {"name":"Maldives","code":"MV","status":"shipping"},
  {"name":"Mali","code":"ML","status":"shipping"},
  {"name":"Malta","code":"MT","status":"shipping"},
  {"name":"Marshall Islands","code":"MH","status":"shipping"},
  {"name":"Martinique","code":"MQ","status":"shipping"},
  {"name":"Mauritania","code":"MR","status":"shipping"},
  {"name":"Mauritius","code":"MU","status":"shipping"},
  {"name":"Mexico","code":"MX","status":"shipping"},
  {"name":"Micronesia","code":"FM","status":"shipping"},
  {"name":"Moldova","code":"MD","status":"shipping"},
  {"name":"Monaco","code":"MC","status":"shipping"},
  {"name":"Mongolia","code":"MN","status":"shipping"},
  {"name":"Montenegro","code":"ME","status":"shipping"},
  {"name":"Montserrat","code":"MS","status":"shipping"},
  {"name":"Morocco","code":"MA","status":"shipping"},
  {"name":"Mozambique","code":"MZ","status":"shipping"},
  {"name":"Namibia","code":"NA","status":"shipping"},
  {"name":"Nepal","code":"NP","status":"shipping"},
  {"name":"Netherlands","code":"NL","status":"shipping"},
  {"name":"New Caledonia","code":"NC","status":"shipping"},
  {"name":"New Zealand","code":"NZ","status":"shipping"},
  {"name":"Nicaragua","code":"NI","status":"shipping"},
  {"name":"Niger","code":"NE","status":"shipping"},
  {"name":"Nigeria","code":"NG","status":"shipping"},
  {"name":"Northern Mariana Islands","code":"MP","status":"shipping"},
  {"name":"Norway","code":"NO","status":"shipping"},
  {"name":"Oman","code":"OM","status":"shipping"},
  {"name":"Pakistan","code":"PK","status":"shipping"},
  {"name":"Palau","code":"PW","status":"shipping"},
  {"name":"Palestine","code":"PS","status":"shipping"},
  {"name":"Panama","code":"PA","status":"shipping"},
  {"name":"Papua New Guinea","code":"PG","status":"shipping"},
  {"name":"Paraguay","code":"PY","status":"shipping"},
  {"name":"Peru","code":"PE","status":"shipping"},
  {"name":"Philippines","code":"PH","status":"shipping"},
  {"name":"Poland","code":"PL","status":"shipping"},
  {"name":"Portugal","code":"PT","status":"shipping"},
  {"name":"Puerto Rico","code":"PR","status":"shipping"},
  {"name":"Qatar","code":"QA","status":"shipping"},
  {"name":"Romania","code":"RO","status":"shipping"},
  {"name":"Russia","code":"RU","status":"shipping"},
  {"name":"Rwanda","code":"RW","status":"shipping"},
  {"name":"Réunion","code":"RE","status":"shipping"},
  {"name":"Samoa","code":"WS","status":"shipping"},
  {"name":"San Marino","code":"SM","status":"shipping"},
  {"name":"Saudi Arabia","code":"SA","status":"shipping"},
  {"name":"Senegal","code":"SN","status":"shipping"},
  {"name":"Serbia","code":"RS","status":"shipping"},
  {"name":"Seychelles","code":"SC","status":"shipping"},
  {"name":"Sierra Leone","code":"SL","status":"shipping"},
  {"name":"Singapore","code":"SG","status":"suspended"},
  {"name":"Slovakia","code":"SK","status":"shipping"},
  {"name":"Slovenia","code":"SI","status":"shipping"},
  {"name":"South Africa","code":"ZA","status":"shipping"},
  {"name":"South Korea","code":"KR","status":"shipping"},
  {"name":"Spain","code":"ES","status":"shipping"},
  {"name":"Sri Lanka","code":"LK","status":"shipping"},
  {"name":"St. Barthélemy","code":"BL","status":"shipping"},
  {"name":"St. Kitts & Nevis","code":"KN","status":"shipping"},
  {"name":"St. Lucia","code":"LC","status":"shipping"},
  {"name":"St. Maarten","code":"SX","status":"shipping"},
  {"name":"St. Martin","code":"MF","status":"shipping"},
  {"name":"St. Vincent","code":"VC","status":"shipping"},
  {"name":"Suriname","code":"SR","status":"shipping"},
  {"name":"Swaziland","code":"SZ","status":"shipping"},
  {"name":"Sweden","code":"SE","status":"shipping"},
  {"name":"Switzerland","code":"CH","status":"shipping"},
  {"name":"Syria","code":"SY","status":":supended"},
  {"name":"Taiwan","code":"TW","status":"shipping"},
  {"name":"Tanzania","code":"TZ","status":"shipping"},
  {"name":"Thailand","code":"TH","status":"shipping"},
  {"name":"Timor-Leste","code":"TL","status":"shipping"},
  {"name":"Togo","code":"TG","status":"shipping"},
  {"name":"Tonga","code":"TO","status":"shipping"},
  {"name":"Trinidad & Tobago","code":"TT","status":"shipping"},
  {"name":"Tunisia","code":"TN","status":"shipping"},
  {"name":"Turkey","code":"TR","status":"shipping"},
  {"name":"Turkmenistan","code":"TM","status":"suspended"},
  {"name":"Turks & Caicos Islands","code":"TC","status":"shipping"},
  {"name":"U.S. Virgin Islands","code":"VI","status":"shipping"},
  {"name":"Uganda","code":"UG","status":"shipping"},
  {"name":"Ukraine","code":"UA","status":"shipping"},
  {"name":"United Arab Emirates","code":"AE","status":"shipping"},
  {"name":"United Kingdom","code":"GB","status":"shipping"},
  {"name":"United States","code":"US","status":"shipping"},
  {"name":"Uruguay","code":"UY","status":"shipping"},
  {"name":"Uzbekistan","code":"UZ","status":"shipping"},
  {"name":"Vanuatu","code":"VU","status":"shipping"},
  {"name":"Vatican City","code":"VA","status":"shipping"},
  {"name":"Venezuela","code":"VE","status":"suspended"},
  {"name":"Vietnam","code":"VN","status":"shipping"},
  {"name":"Wallis & Futuna","code":"WF","status":"shipping"},
  {"name":"Yemen","code":"YE","status":"suspended"},
  {"name":"Zambia","code":"ZM","status":"shipping"},
  {"name":"Zimbabwe","code":"ZW","status":"shipping"}
];

/**
 * Country states or provinces used in mailing addresses within
 * Australia, Canada, China, Malaysia, Mexico, Spain, United States
 */
export const countryProvinces = [
  {
    "name": "Australia",
    "code": "AU",
    "provinces": [
      {"name": "Australian Capital Territory", "code": "ACT"},
      {"name": "New South Wales", "code": "NSW"},
      {"name": "Northern Territory", "code": "NT"},
      {"name": "Queensland", "code": "QLD"},
      {"name": "South Australia", "code": "SA"},
      {"name": "Tasmania", "code": "TAS"},
      {"name": "Victoria", "code": "VIC"},
      {"name": "Western Australia", "code": "WA"}
    ]
  },
  {
    "name": "Canada",
    "code": "CA",
    "provinces": [
      {"name": "Alberta", "code": "AB"},
      {"name": "British Columbia", "code": "BC"},
      {"name": "Manitoba", "code": "MB"},
      {"name": "New Brunswick", "code": "NB"},
      {"name": "Newfoundland and Labrador", "code": "NL"},
      {"name": "Northwest Territories", "code": "NT"},
      {"name": "Nova Scotia", "code": "NS"},
      {"name": "Nunavut", "code": "NU"},
      {"name": "Ontario", "code": "ON"},
      {"name": "Prince Edward Island", "code": "PE"},
      {"name": "Quebec", "code": "QC"},
      {"name": "Saskatchewan", "code": "SK"},
      {"name": "Yukon", "code": "YT"}
    ]
  },
  {
    "name": "China",
    "code": "CN",
    "provinces": [
      { "name": "Anhui (安徽省)", "code": "CN-AH" },
      { "name": "Fujian (福建省)", "code": "CN-FJ" },
      { "name": "Gansu (甘肃省)", "code": "CN-GS" },
      { "name": "Guangdong (广东省)", "code": "CN-GD" },
      { "name": "Guizhou (贵州省)", "code": "CN-GZ" },
      { "name": "Hainan (海南省)", "code": "CN-HI" },
      { "name": "Hebei (河北省)", "code": "CN-HE" },
      { "name": "Heilongjiang (黑龙江省)", "code": "CN-HL"},
      { "name": "Henan (河南省)", "code": "CN-HA" },
      { "name": "Hubei (湖北省)", "code": "CN-HB" },
      { "name": "Hunan (湖南省)", "code": "CN-HN" },
      { "name": "Jiangsu (江苏省)", "code": "CN-JS" },
      { "name": "Jiangxi (江西省)", "code": "CN-JX" },
      { "name": "Jilin (吉林省)", "code": "CN-JL" },
      { "name": "Liaoning (辽宁省)", "code": "CN-LN" },
      { "name": "Qinghai (青海省)", "code": "CN-QH" },
      { "name": "Shaanxi (陕西省)", "code": "CN-SN" },
      { "name": "Shandong (山东省)", "code": "CN-SD" },
      { "name": "Shanxi (山西省)", "code": "CN-SX" },
      { "name": "Sichuan (四川省)", "code": "CN-SC" },
      { "name": "Yunnan (云南省)", "code": "CN-YN" },
      { "name": "Zhejiang (浙江省)", "code": "CN-ZJ" }
    ]
  },
  {
    "name": "Malaysia",
    "code": "MY",
    "provinces": [
      {"name": "Johor", "code": "JHR"},
      {"name": "Kedah", "code": "KDH"},
      {"name": "Kelantan", "code": "KTN"},
      {"name": "Kuala Lumpur", "code": "KUL"},
      {"name": "Labuan", "code": "LBN"},
      {"name": "Melaka", "code": "MLK"},
      {"name": "Negeri Sembilan", "code": "NSN"},
      {"name": "Pahang", "code": "PHG"},
      {"name": "Perak", "code": "PRK"},
      {"name": "Perlis", "code": "PLS"},
      {"name": "Pulau Pinang", "code": "PNG"},
      {"name": "Putrajaya", "code": "PJY"},
      {"name": "Sabah", "code": "SBH"},
      {"name": "Sarawak", "code": "SWK"},
      {"name": "Selangor", "code": "SGR"},
      {"name": "Terengganu", "code": "TRG"}
    ]
  },
  {
    "name": "Mexico",
    "code": "MX",
    "provinces": [
      { "name": "Aguascalientes", "code": "MX-AG" },
      { "name": "Baja California ", "code": "MX-BN" },
      { "name": "Baja California Sur ", "code": "MX-BS" },
      { "name": "Campeche", "code": "MX-CP" },
      { "name": "Chiapas ", "code": "MX-CS" },
      { "name": "Chihuahua ", "code": "MX-CI" },
      { "name": "Coahuila", "code": "MX-CH" },
      { "name": "Colima", "code": "MX-CL" },
      { "name": "Mexico City ", "code": "MX-DF" },
      { "name": "Durango ", "code": "MX-DG" },
      { "name": "Guanajuato", "code": "MX-GJ" },
      { "name": "Guerrero", "code": "MX-GE" },
      { "name": "Hidalgo ", "code": "MX-HD" },
      { "name": "Jalisco ", "code": "MX-JA" },
      { "name": "México Edomex. or", "code": "MX-MX" },
      { "name": "Michoacán ", "code": "MX-MC" },
      { "name": "Morelos ", "code": "MX-MR" },
      { "name": "Nayarit ", "code": "MX-NA" },
      { "name": "Nuevo León", "code": "MX-NL" },
      { "name": "Oaxaca", "code": "MX-OA" },
      { "name": "Puebla", "code": "MX-PU" },
      { "name": "Querétaro ", "code": "MX-QE" },
      { "name": "Quintana Roo Q. Roo. or", "code": "MX-QI" },
      { "name": "San Luis Potosí ", "code": "MX-SL" },
      { "name": "Sinaloa ", "code": "MX-SI" },
      { "name": "Sonora", "code": "MX-SO" },
      { "name": "Tabasco ", "code": "MX-TB" },
      { "name": "Tamaulipas", "code": "MX-TA" },
      { "name": "Tlaxcala", "code": "MX-TL" },
      { "name": "Veracruz", "code": "MX-VC" },
      { "name": "Yucatán ", "code": "MX-YU" },
      { "name": "Zacatecas ", "code": "MX-ZA" }
    ]
  },
  {
    "name": "Spain",
    "code": "ES",
    "provinces": [
      {"name": "A Coruña", "code": "C"},
      {"name": "Álava", "code": "VI"},
      {"name": "Albacete", "code": "AB"},
      {"name": "Alicante", "code": "A"},
      {"name": "Almería", "code": "AL"},
      {"name": "Asturias", "code": "O"},
      {"name": "Ávila", "code": "AV"},
      {"name": "Badajoz", "code": "BA"},
      {"name": "Baleares", "code": "PM"},
      {"name": "Barcelona", "code": "B"},
      {"name": "Burgos", "code": "BU"},
      {"name": "Cáceres", "code": "CC"},
      {"name": "Cádiz", "code": "CA"},
      {"name": "Cantabria", "code": "S"},
      {"name": "Castellón", "code": "CS"},
      {"name": "Ceuta", "code": "CE"},
      {"name": "Ciudad Real", "code": "CR"},
      {"name": "Córdoba", "code": "CO"},
      {"name": "Cuenca", "code": "CU"},
      {"name": "Girona", "code": "GI"},
      {"name": "Granada", "code": "GR"},
      {"name": "Guadalajara", "code": "GU"},
      {"name": "Guipúzcoa", "code": "SS"},
      {"name": "Huelva", "code": "H"},
      {"name": "Huesca", "code": "HU"},
      {"name": "Jaén", "code": "J"},
      {"name": "La Rioja", "code": "LO"},
      {"name": "Las Palmas", "code": "GC"},
      {"name": "León", "code": "LE"},
      {"name": "Lleida", "code": "L"},
      {"name": "Lugo", "code": "LU"},
      {"name": "Madrid", "code": "M"},
      {"name": "Málaga", "code": "MA"},
      {"name": "Melilla", "code": "ML"},
      {"name": "Murcia", "code": "MU"},
      {"name": "Navarra", "code": "NA"},
      {"name": "Ourense", "code": "OR"},
      {"name": "Palencia", "code": "P"},
      {"name": "Pontevedra", "code": "PO"},
      {"name": "Salamanca", "code": "SA"},
      {"name": "Segovia", "code": "SG"},
      {"name": "Sevilla", "code": "SE"},
      {"name": "Soria", "code": "SO"},
      {"name": "Tarragona", "code": "T"},
      {"name": "Tenerife", "code": "TF"},
      {"name": "Teruel", "code": "TE"},
      {"name": "Toledo", "code": "TO"},
      {"name": "Valencia", "code": "V"},
      {"name": "Valladolid", "code": "VA"},
      {"name": "Vizcaya", "code": "BI"},
      {"name": "Zamora", "code": "ZA"},
      {"name": "Zaragoza", "code": "Z"}
    ]
  },
  {
    "name": "United States",
    "code": "US",
    "provinces": [
      {"name": "Alabama", "code": "AL"},
      {"name": "Alaska", "code": "AK"},
      {"name": "American Samoa", "code": "AS"},
      {"name": "Arizona", "code": "AZ"},
      {"name": "Arkansas", "code": "AR"},
      {"name": "California", "code": "CA"},
      {"name": "Colorado", "code": "CO"},
      {"name": "Connecticut", "code": "CT"},
      {"name": "Delaware", "code": "DE"},
      {"name": "District Of Columbia", "code": "DC"},
      {"name": "Federated States Of Micronesia", "code": "FM"},
      {"name": "Florida", "code": "FL"},
      {"name": "Georgia", "code": "GA"},
      {"name": "Guam", "code": "GU"},
      {"name": "Hawaii", "code": "HI"},
      {"name": "Idaho", "code": "ID"},
      {"name": "Illinois", "code": "IL"},
      {"name": "Indiana", "code": "IN"},
      {"name": "Iowa", "code": "IA"},
      {"name": "Kansas", "code": "KS"},
      {"name": "Kentucky", "code": "KY"},
      {"name": "Louisiana", "code": "LA"},
      {"name": "Maine", "code": "ME"},
      {"name": "Marshall Islands", "code": "MH"},
      {"name": "Maryland", "code": "MD"},
      {"name": "Massachusetts", "code": "MA"},
      {"name": "Michigan", "code": "MI"},
      {"name": "Minnesota", "code": "MN"},
      {"name": "Mississippi", "code": "MS"},
      {"name": "Missouri", "code": "MO"},
      {"name": "Montana", "code": "MT"},
      {"name": "Nebraska", "code": "NE"},
      {"name": "Nevada", "code": "NV"},
      {"name": "New Hampshire", "code": "NH"},
      {"name": "New Jersey", "code": "NJ"},
      {"name": "New Mexico", "code": "NM"},
      {"name": "New York", "code": "NY"},
      {"name": "North Carolina", "code": "NC"},
      {"name": "North Dakota", "code": "ND"},
      {"name": "Northern Mariana Islands", "code": "MP"},
      {"name": "Ohio", "code": "OH"},
      {"name": "Oklahoma", "code": "OK"},
      {"name": "Oregon", "code": "OR"},
      {"name": "Palau", "code": "PW"},
      {"name": "Pennsylvania", "code": "PA"},
      {"name": "Puerto Rico", "code": "PR"},
      {"name": "Rhode Island", "code": "RI"},
      {"name": "South Carolina", "code": "SC"},
      {"name": "South Dakota", "code": "SD"},
      {"name": "Tennessee", "code": "TN"},
      {"name": "Texas", "code": "TX"},
      {"name": "Utah", "code": "UT"},
      {"name": "Vermont", "code": "VT"},
      {"name": "Virgin Islands", "code": "VI"},
      {"name": "Virginia", "code": "VA"},
      {"name": "Washington", "code": "WA"},
      {"name": "West Virginia", "code": "WV"},
      {"name": "Wisconsin", "code": "WI"},
      {"name": "Wyoming", "code": "WY"}
    ]
  }
];